# Generated by Django 4.0.4 on 2022-04-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_department_managers_employee_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programminglanguage',
            options={'ordering': ['name']},
        ),
    ]
