# Generated by Django 4.0.4 on 2022-04-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_programminglanguage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='languages',
            field=models.ManyToManyField(to='backend.programminglanguage'),
        ),
    ]
