# Generated by Django 3.2 on 2022-04-20 10:39

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('floor', models.PositiveIntegerField()),
            ],
            managers=[
                ('deparments', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            managers=[
                ('languages', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.IntegerField(choices=[('1', 'Male'), ('2', 'Female')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='backend.department')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='backend.programminglanguage')),
            ],
            managers=[
                ('employees', django.db.models.manager.Manager()),
            ],
        ),
    ]
