# Generated by Django 4.0.3 on 2022-04-25 12:47

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='department',
            managers=[
                ('departments', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(check=models.Q(('age__lt', 100)), name='Yosh juda katta bo`ldi'),
        ),
    ]
