# Generated by Django 4.0.3 on 2022-04-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_employee_gender_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='department',
            name='Department manfiy qavatda bo`lmidi',
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(check=models.Q(('floor__lt', 100)), name='Xorazmda 100 qavatli bino nishidi'),
        ),
    ]
