# Generated by Django 3.2 on 2021-05-30 09:07

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_test_questions_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testone',
            options={'ordering': ['test__id', 'number']},
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(default='tests/default.png', upload_to=app.models.question_image_directory_path),
        ),
    ]
