# Generated by Django 3.2 on 2022-04-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='To`liq ismi')),
            ],
            options={
                'verbose_name': 'Muallif',
                'verbose_name_plural': 'Mualliflar',
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=255, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Familyasi')),
                ('username', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Teg',
                'verbose_name_plural': 'Teglar',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Sharxi')),
                ('price', models.FloatField(verbose_name='Narxi')),
                ('image', models.ImageField(upload_to='book_images/', verbose_name='Rasm')),
                ('tags', models.ManyToManyField(to='backend.Tag', verbose_name='Teglar')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
            },
        ),
    ]
