# Generated by Django 3.2 on 2022-04-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220412_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='password',
            new_name='pword',
        ),
    ]
