# Generated by Django 3.2 on 2022-04-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_password_author_pword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='pword',
            new_name='phone_number',
        ),
    ]
