# Generated by Django 3.2 on 2022-04-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_pword_author_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='phone_number',
            new_name='name',
        ),
    ]
