# Generated by Django 3.2 on 2022-04-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_phone_number_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='full_name',
        ),
    ]
