# Generated by Django 4.0.3 on 2022-04-25 11:48

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20220412_1909'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='botuser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='Usernameni tekshirish'),
        ),
    ]
