# Generated by Django 4.0.3 on 2022-04-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_botuser_usernameni tekshirish'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('price__lt', 10000)), name='Katta summa kiritilgan'),
        ),
    ]
